// src/types/index.ts

// Tag applied to a phrase. A phrase can have multiple tags.
export interface Tag {
    id: string; //id is a UUID generated by the frontend
    name: string;
}

// Phrase is the core data structure, representing a phrase said by a person.
export interface Phrase {
    id: string; //id is a UUID generated by the frontend
    text: string | null; // the text of the phrase, can be null if the phrase is awaiting transciption
    created_at: number; // timestamp in milliseconds
    updated_at: number; // timestamp in milliseconds
    source: "entered" | "recorded" // the source of the phrase, either entered by the user or recorded by the system
    recording_path: string | null; // the path to the recording of the phrase, can be null if the phrase is entered by the user
    speaker: string | null; // the name of the speaker, can be null if the speaker is unknown or awaiting entry
    language: string | null; // the language of the phrase, can be null if the language is unknown or awaiting entry
    tags: Tag[]; // the tags applied to the phrase, can be null if no tags are applied
}